env:
  global:
    - CC_TEST_REPORTER_ID=25cdbdb9a3ca7aebb372300017b87e21255fa3db89d11c72cc96fb0b993e5019

language: php

php:
  - 7.1.9

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer require codeclimate/php-test-reporter --dev
  - composer install
  - php artisan key:generate

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=25cdbdb9a3ca7aebb372300017b87e21255fa3db89d11c72cc96fb0b993e5019 vendor/bin/test-reporter --stdout > codeclimate.json
  - "sh -c 'curl -X POST -d @codeclimate.json -H \"Content-Type: application/json\" -H \"User-Agent: Code Climate PHP Test reporter\" https://codeclimate.com/test_reports ;'"